# GoReleaser configuration for terraform-provider-mikrotik
# See: https://goreleaser.com for documentation
#
# This config produces:
# - Multi-platform binaries (Linux, macOS, Windows, FreeBSD)
# - GPG-signed SHA256 checksums
# - GitHub Release with changelog
# - Terraform Registry compatible artifacts
#
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: terraform-provider-mikrotik
    binary: '{{ .ProjectName }}_v{{ .Version }}'
    main: .
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}'
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
      - '386'
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64

archives:
  - id: terraform-provider-mikrotik
    format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - artifacts: checksum
    cmd: gpg
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  github:
    owner: lkolo-prez
    name: terraform-provider-mikrotik
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Terraform Provider for MikroTik RouterOS {{ .Tag }}
    
    ### Installation
    
    This provider is published to the [Terraform Registry](https://registry.terraform.io/providers/ddelnano/mikrotik/latest).
    
    ```hcl
    terraform {
      required_providers {
        mikrotik = {
          source  = "ddelnano/mikrotik"
          version = "~> {{ .Version }}"
        }
      }
    }
    ```
    
    ### What's Changed
  footer: |
    **Full Changelog**: https://github.com/lkolo-prez/terraform-provider-mikrotik/compare/{{ .PreviousTag }}...{{ .Tag }}
    
    ### Verification
    
    All artifacts are signed with GPG. Verify checksums:
    ```bash
    gpg --verify {{ .ProjectName }}_{{ .Version }}_SHA256SUMS.sig {{ .ProjectName }}_{{ .Version }}_SHA256SUMS
    sha256sum -c {{ .ProjectName }}_{{ .Version }}_SHA256SUMS
    ```

changelog:
  use: github
  sort: asc
  abbrev: 7
  groups:
    - title: 'Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Documentation'
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: 'Tests'
      regexp: '^.*?test(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: 'CI/CD'
      regexp: '^.*?ci(\([[:word:]]+\))??!?:.+$'
      order: 5
    - title: 'Other Changes'
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - typo
      - Merge pull request
      - Merge branch
