package mikrotik

import (
	"context"

	"github.com/ddelnano/terraform-provider-mikrotik/client"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"

	tftypes "github.com/hashicorp/terraform-plugin-framework/types"
)

type snmp struct {
	client *client.Mikrotik
}

// Ensure the implementation satisfies the expected interfaces.
var (
	_ resource.Resource              = &snmp{}
	_ resource.ResourceWithConfigure = &snmp{}
)

// NewSnmpResource is a helper function to simplify the provider implementation.
func NewSnmpResource() resource.Resource {
	return &snmp{}
}

func (r *snmp) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	r.client = req.ProviderData.(*client.Mikrotik)
}

func (r *snmp) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_snmp"
}

func (r *snmp) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages SNMP configuration for network monitoring. Singleton resource - only one instance exists per router.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "The ID of the SNMP configuration (always '*0' - singleton resource).",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"enabled": schema.BoolAttribute{
				Description: "Enable SNMP service. Default: false.",
				Optional:    true,
				Computed:    true,
				Default:     booldefault.StaticBool(false),
			},
			"contact": schema.StringAttribute{
				Description: "System contact information (sysContact). Example: 'noc@company.com' or 'Network Operations Center'.",
				Optional:    true,
			},
			"location": schema.StringAttribute{
				Description: "System location (sysLocation). Example: 'Datacenter A, Rack 12' or 'Building 5, Floor 3'.",
				Optional:    true,
			},
			"engine_id": schema.StringAttribute{
				Description: "SNMPv3 engine ID. Read-only, auto-generated by RouterOS.",
				Computed:    true,
			},
			"trap_version": schema.StringAttribute{
				Description: "SNMP trap version: '1' or '2'. Default: '1'.",
				Optional:    true,
				Computed:    true,
				Default:     stringdefault.StaticString("1"),
				Validators: []validator.String{
					stringvalidator.OneOf("1", "2"),
				},
			},
			"trap_community": schema.StringAttribute{
				Description: "SNMP community string for traps. Default: 'public'.",
				Optional:    true,
				Computed:    true,
				Default:     stringdefault.StaticString("public"),
				Sensitive:   true,
			},
			"trap_target": schema.StringAttribute{
				Description: "Trap target IP address or hostname. Empty = no traps sent.",
				Optional:    true,
			},
			"trap_generators": schema.StringAttribute{
				Description: "Comma-separated list of trap generators. Examples: 'temp-exception', 'interfaces'. Empty = all generators.",
				Optional:    true,
			},
		},
	}
}

// snmpModel maps the resource schema data.
type snmpModel struct {
	Id             tftypes.String `tfsdk:"id"`
	Enabled        tftypes.Bool   `tfsdk:"enabled"`
	Contact        tftypes.String `tfsdk:"contact"`
	Location       tftypes.String `tfsdk:"location"`
	EngineId       tftypes.String `tfsdk:"engine_id"`
	TrapVersion    tftypes.String `tfsdk:"trap_version"`
	TrapCommunity  tftypes.String `tfsdk:"trap_community"`
	TrapTarget     tftypes.String `tfsdk:"trap_target"`
	TrapGenerators tftypes.String `tfsdk:"trap_generators"`
}

// Create creates the resource and sets the initial Terraform state.
func (r *snmp) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data snmpModel

	// Read Terraform plan data into the model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	snmpConfig := &client.Snmp{
		Enabled:        data.Enabled.ValueBool(),
		Contact:        data.Contact.ValueString(),
		Location:       data.Location.ValueString(),
		TrapVersion:    data.TrapVersion.ValueString(),
		TrapCommunity:  data.TrapCommunity.ValueString(),
		TrapTarget:     data.TrapTarget.ValueString(),
		TrapGenerators: data.TrapGenerators.ValueString(),
	}

	updated, err := r.client.UpdateSnmp(snmpConfig)
	if err != nil {
		resp.Diagnostics.AddError("Error configuring SNMP", err.Error())
		return
	}

	// Map response to state
	data.Id = tftypes.StringValue("*0")
	data.EngineId = tftypes.StringValue(updated.EngineId)

	// Save data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// Read refreshes the Terraform state with the latest data.
func (r *snmp) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data snmpModel

	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	snmpConfig, err := r.client.GetSnmp()
	if err != nil {
		resp.Diagnostics.AddError("Error reading SNMP configuration", err.Error())
		return
	}

	// Map response to state
	data.Enabled = tftypes.BoolValue(snmpConfig.Enabled)
	data.Contact = tftypes.StringValue(snmpConfig.Contact)
	data.Location = tftypes.StringValue(snmpConfig.Location)
	data.EngineId = tftypes.StringValue(snmpConfig.EngineId)
	data.TrapVersion = tftypes.StringValue(snmpConfig.TrapVersion)
	data.TrapCommunity = tftypes.StringValue(snmpConfig.TrapCommunity)
	data.TrapTarget = tftypes.StringValue(snmpConfig.TrapTarget)
	data.TrapGenerators = tftypes.StringValue(snmpConfig.TrapGenerators)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// Update updates the resource and sets the updated Terraform state on success.
func (r *snmp) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data snmpModel

	// Read Terraform plan data into the model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	snmpConfig := &client.Snmp{
		Enabled:        data.Enabled.ValueBool(),
		Contact:        data.Contact.ValueString(),
		Location:       data.Location.ValueString(),
		TrapVersion:    data.TrapVersion.ValueString(),
		TrapCommunity:  data.TrapCommunity.ValueString(),
		TrapTarget:     data.TrapTarget.ValueString(),
		TrapGenerators: data.TrapGenerators.ValueString(),
	}

	updated, err := r.client.UpdateSnmp(snmpConfig)
	if err != nil {
		resp.Diagnostics.AddError("Error updating SNMP configuration", err.Error())
		return
	}

	// Map response to state
	data.EngineId = tftypes.StringValue(updated.EngineId)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// Delete deletes the resource and removes the Terraform state on success.
func (r *snmp) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data snmpModel

	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Disable SNMP instead of deleting (singleton resource)
	snmpConfig := &client.Snmp{
		Enabled: false,
	}

	_, err := r.client.UpdateSnmp(snmpConfig)
	if err != nil {
		resp.Diagnostics.AddError("Error disabling SNMP", err.Error())
		return
	}
}
